### ISSUE TITLE
Some latex equations are not rendered in webpage

### ISSUE THREAD

**Issue by jspanchu** [Kitware/vtk-book#14]
It's not apparent if this is a known issue. Some equations are not rendered in the webpage. 

See https://book.vtk.org/en/latest/VTKBook/03Chapter3.html#coordinate-transformation

![image](https://github.com/Kitware/vtk-book/assets/40538987/899ff168-618b-4a4b-80f9-d3ff7b0cf3b4)

However, https://examples.vtk.org/site/VTKBook/03Chapter3/#37-coordinate-transformation is able to render those equations.

**Comment by spookylukey** [comment]
@jcfr This issue is not fixed - the web page still does not render those equations, they still appear as  "\tag not allowed in split environment" - see https://book.vtk.org/en/latest/VTKBook/03Chapter3.html#coordinate-transformation

Please can we re-open this? Perhaps the fix was not enough, or the web version has not been rebuilt?

Thanks!

**Comment by ChristosT** [comment]
Indeed it looks like the last build failed. https://readthedocs.org/projects/vtk-book/builds/
